move this
somehow @Perkedel/After-Church broke? we can't upload at all

```
Enumerating objects: 38, done.
Counting objects: 100% (38/38), done.
Delta compression using up to 12 threads
Compressing objects: 100% (26/26), done.
error: RPC failed; curl 16 Error in the HTTP2 framing layer
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (29/29), 156.73 MiB | 2.14 MiB/s, done.
Total 29 (delta 8), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date
```